---
title: "analysis"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list = ls())
library(tidyverse); library(data.table); library(sandwich); library(lmtest); library(BFpack)
```

```{r}
# bayes factors
compute_bf <- function(model, n, hypothesis = NULL) {
    if (class(model)[1] == "coeftest") {
        message("Model class: coeftest")
        bf <- BF(model[, 1], Sigma = diag(model[, 2]^2), n = n, hypothesis = hypothesis)
    } else {
        bf <- BF(model, n = nobs(model), hypothesis = hypothesis)
    }
    return(bf)
}
```

```{r}
dt1 <- fread("../data/clean/data_wide_centered.csv")
```

```{r remove people}
dt1 <- dt1[IP_Hub_recommend_block == 0, ]
dt1[, n_distinct(responseid)]
```

```{r model1}
# Model 1 (only false headlines): sharing ~ ideology + conscientiousness + ideology:conscientiousness

m1_1 <- glm(share ~ demrep_c * bfi_c, family = binomial, data = dt1[veracity == 0])
summary(m1_1)
m1_1c <- coeftest(m1_1, vcovCL(m1_1, ~ responseid + headline_id, NULL, fix = FALSE))
m1_1c

# BF
(samplesize <- nobs(m1_1))
bf <- compute_bf(m1_1c, samplesize, "demrep_c:bfi_c = 0")
summary(bf)
```

```{r model2}
# Model 2 (only false headlines): sharing ~ ideology * ( conscientiousness + extraversion + agreeableness + negative emotionality + openness + age + gender + education + attentiveness + thinking styles)

m2_1 <- glm(share ~ demrep_c * (bfi_c + bfi_e + bfi_a + bfi_n + bfi_o + 
                                  age + gender + edu + attention_score + ctsq_aot), 
            family = binomial, data = dt1[veracity == 0])
summary(m2_1)
m2_1c <- coeftest(m2_1, vcovCL(m2_1, ~ responseid + headline_id, NULL))
m2_1c

# BF
(samplesize <- nobs(m2_1))
bf <- compute_bf(m2_1c, samplesize, "demrep_c:bfi_c = 0")
summary(bf)
```

